### ISSUE TITLE
No license means not free software

### ISSUE THREAD

**Issue by fabianegli** [wilhelm-lab/proteomicsdb-views#1]
Dear ProteomicsDB creators

Thank you for the great resource which is ProteomicsDB and these support repositories to ease community contributions.

I would like to note that the lack of a license in this and related repositories make them heavily copyright protected and others are de facto exempt from using them. The latest paper however states that reusability is intended:

>All of these levels are publicly available on GitHub as separate repositories. We expect that this will further improvement the findability and accessibility, but particularly the reusability of the code base of ProteomicsDB.

From https://academic.oup.com/nar/article/50/D1/D1541/6430496?login=false

Please add a license to these repositories so it become legal for everyone to actually use them in their work.

Kind regards,
Fabian

**Comment by jmueller95** [comment]
Dear Fabian,
thanks for pointing this out! We simply forgot back then...
The code lives here now and is properly licensed: https://github.com/wilhelm-lab/proteomicsdb-vue
